//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELETELOG
    {
        public decimal DELETEID { get; set; }
        public string TABLENAME { get; set; }
        public string MESSAGE { get; set; }
        public string OBJECTID { get; set; }
        public string OBJECTNAME { get; set; }
        public Nullable<System.DateTime> DELETEDDATE { get; set; }
    }
}
