//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMPOSTINGEVENT2
    {
        public string LOCATION { get; set; }
        public string ID { get; set; }
        public string ORIGINALID { get; set; }
        public string OWNERTABLE { get; set; }
        public string TRADEID { get; set; }
        public decimal SEQNUM { get; set; }
        public string ASSETID { get; set; }
        public string EVENT { get; set; }
        public decimal AMOUNT { get; set; }
        public string CCY { get; set; }
        public string POSTINGDATE { get; set; }
        public string VALUEDATE { get; set; }
        public string BOOKINGDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string ACCOUNTID { get; set; }
        public string DRORCR { get; set; }
        public string POSTINGTYPE { get; set; }
        public string EXTRACTFLAG { get; set; }
        public string EXTRACTDATE { get; set; }
        public decimal PROCESSFLAG { get; set; }
        public string SETTLEACCTTYPE { get; set; }
        public string SETTLEACCTID { get; set; }
        public string ALTOWNERTABLE { get; set; }
        public string ALTTRADEID { get; set; }
        public decimal ALTVERSION { get; set; }
        public decimal VERSION { get; set; }
        public string BENEFICIARY { get; set; }
        public string CUSTROLE { get; set; }
        public string ACCTTYPE { get; set; }
        public string ORIGSETTLECCY { get; set; }
        public decimal ORIGSETTLEAMT { get; set; }
        public string OBJID { get; set; }
        public string GLDATE { get; set; }
    }
}
