//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MV_OBJ_WITH_PEG
    {
        public long OBJECT_ID { get; set; }
        public string OBJECT_HAPPY_NAME { get; set; }
        public string OBJECT_TYPE { get; set; }
        public Nullable<long> APPLICATION_ID { get; set; }
        public string QUICK_ACCESS { get; set; }
        public decimal OBJECT_NAME_ID { get; set; }
    }
}
