//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MV_STORYBOARD_LATEST
    {
        public Nullable<long> STORYBOARD_ID { get; set; }
        public long STORYBOARD_DETAIL_ID { get; set; }
        public Nullable<short> TEST_MODE { get; set; }
        public Nullable<decimal> MX_STB_LTST_ID { get; set; }
    }
}
