//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_TEST_REPORT_STEPS_COMMENT
    {
        public long ID { get; set; }
        public long TEST_REPORT_STEP_ID { get; set; }
        public short TEST_MODE { get; set; }
        public string COMMENT { get; set; }
    }
}
