//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_TC_DATA_SUMMARY
    {
        public long ID { get; set; }
        public Nullable<long> DATA_SUMMARY_ID { get; set; }
        public Nullable<long> TEST_CASE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
    
        public virtual T_TEST_CASE_SUMMARY T_TEST_CASE_SUMMARY { get; set; }
        public virtual T_TEST_DATA_SUMMARY T_TEST_DATA_SUMMARY { get; set; }
    }
}
