//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_FOLDER_FILTER
    {
        public long REL_FOLDER_FILTER_ID { get; set; }
        public Nullable<long> FOLDER_ID { get; set; }
        public Nullable<long> FILTER_ID { get; set; }
    }
}
