//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_OBJ_APP
    {
        public long RELATIONSHIP_ID { get; set; }
        public long OBJECT_ID { get; set; }
        public long APPLICATION_ID { get; set; }
    
        public virtual T_REGISTERED_APPS T_REGISTERED_APPS { get; set; }
        public virtual T_REGISTED_OBJECT T_REGISTED_OBJECT { get; set; }
    }
}
