//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_DB_QUERY
    {
        public long DB_QUERY_ID { get; set; }
        public Nullable<long> QUERY_ID { get; set; }
        public Nullable<long> DATABASE_CONN_ID { get; set; }
    
        public virtual T_DATABASE_CONNECTIONS T_DATABASE_CONNECTIONS { get; set; }
    }
}
