//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_LOOKUP
    {
        public long LOOKUP_ID { get; set; }
        public string TABLE_NAME { get; set; }
        public string FIELD_NAME { get; set; }
        public Nullable<short> VALUE { get; set; }
        public string DISPLAY_NAME { get; set; }
        public Nullable<short> STATUS { get; set; }
    }
}
