//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AXIS_LIST
    {
        public long AXIS_LIST_ID { get; set; }
        public Nullable<long> QUERY_ID { get; set; }
        public Nullable<short> COMMAND_TYPE_ID { get; set; }
        public Nullable<short> X_AXIS { get; set; }
        public Nullable<short> Y_AXIS { get; set; }
        public Nullable<short> Z_AXIS { get; set; }
    
        public virtual T_QUERY T_QUERY { get; set; }
    }
}
