//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BASELINE_DATA_SUMMARY
    {
        public T_BASELINE_DATA_SUMMARY()
        {
            this.T_BASELINE_DATA_DETAIL = new HashSet<T_BASELINE_DATA_DETAIL>();
        }
    
        public decimal DATA_BASE_OBJ_ID { get; set; }
        public Nullable<long> DATA_SUMMARY_ID { get; set; }
        public Nullable<decimal> DATA_BASE_OBJ_PARENT_ID { get; set; }
        public string OBJECT_HAPPY_NAME { get; set; }
        public Nullable<short> ORDER_ID { get; set; }
    
        public virtual ICollection<T_BASELINE_DATA_DETAIL> T_BASELINE_DATA_DETAIL { get; set; }
    }
}
