//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COMPARE_CONNECTIONS
    {
        public decimal DBCONN_ID { get; set; }
        public string DBCONN_NAME { get; set; }
        public string TYPE { get; set; }
        public string HOST { get; set; }
        public string PORT { get; set; }
        public string PROTOCOL { get; set; }
        public string SERVICE_NAME { get; set; }
        public string USERID { get; set; }
        public string PASSWORD { get; set; }
    }
}
