//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DATABASE_CONNECTIONS
    {
        public T_DATABASE_CONNECTIONS()
        {
            this.REL_DB_QUERY = new HashSet<REL_DB_QUERY>();
        }
    
        public long CONNECTION_ID { get; set; }
        public string CONNECTION_NAME { get; set; }
        public Nullable<short> CONNECTION_TYPE { get; set; }
        public string HOST_NAME { get; set; }
        public Nullable<int> PORT_NUMBER { get; set; }
        public string PROTOCOL { get; set; }
        public string SERVICE_NAME { get; set; }
        public string DB_SID { get; set; }
        public string DB_USERNAME { get; set; }
        public string DB_PASSWORD { get; set; }
        public string CONNECTION_STRING { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<short> IS_TESTED { get; set; }
        public Nullable<System.DateTime> LAST_TESTED { get; set; }
        public string ERROR_MESSAGE { get; set; }
    
        public virtual ICollection<REL_DB_QUERY> REL_DB_QUERY { get; set; }
    }
}
