//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DBCONNECTION
    {
        public long DBCONNECTION_ID { get; set; }
        public string DATABASENAME { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string HOST { get; set; }
        public string PORT { get; set; }
        public string SERVICENAME { get; set; }
        public string DECODE_METHOD { get; set; }
        public string SCHEMA { get; set; }
        public byte[] DATABASE_VALUE { get; set; }
    
        public virtual T_QUERY T_QUERY { get; set; }
    }
}
