//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FOLDER_FILTER
    {
        public long FILTER_ID { get; set; }
        public string FILTER_NAME { get; set; }
        public string PROJECT_IDS { get; set; }
        public string STORYBOARD_IDS { get; set; }
    }
}
