//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GRIDLIST
    {
        public decimal ID { get; set; }
        public string COLUMNNAME { get; set; }
        public string COLUMNSIZE { get; set; }
        public decimal GRID_ID { get; set; }
        public decimal USER_ID { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
    }
}
