//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GUI_COMPONENT_TYPE_DIC
    {
        public T_GUI_COMPONENT_TYPE_DIC()
        {
            this.T_DIC_RELATION_KEYWORD = new HashSet<T_DIC_RELATION_KEYWORD>();
            this.T_REGISTED_OBJECT = new HashSet<T_REGISTED_OBJECT>();
        }
    
        public long TYPE_ID { get; set; }
        public string TYPE_NAME { get; set; }
        public Nullable<short> APPLICATION_TYPE_ID { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<T_DIC_RELATION_KEYWORD> T_DIC_RELATION_KEYWORD { get; set; }
        public virtual ICollection<T_REGISTED_OBJECT> T_REGISTED_OBJECT { get; set; }
    }
}
