//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PROJECT_DATA_SOURCE
    {
        public long PRO_DBS_ID { get; set; }
        public Nullable<long> PROJECT_ID { get; set; }
        public Nullable<long> DATA_SOURCE_ID { get; set; }
    
        public virtual T_TEST_PROJECT T_TEST_PROJECT { get; set; }
    }
}
