//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QUERY
    {
        public T_QUERY()
        {
            this.T_AXIS_LIST = new HashSet<T_AXIS_LIST>();
        }
    
        public long QUERY_ID { get; set; }
        public string QUERY_NAME { get; set; }
        public string QUERY_DESC { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<long> CONN_ID { get; set; }
    
        public virtual T_DATABASE_CONNECTIONS T_DATABASE_CONNECTIONS { get; set; }
        public virtual ICollection<T_AXIS_LIST> T_AXIS_LIST { get; set; }
    }
}
