//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REGISTERED_APPS
    {
        public T_REGISTERED_APPS()
        {
            this.REL_OBJ_APP = new HashSet<REL_OBJ_APP>();
        }
    
        public long APPLICATION_ID { get; set; }
        public string APP_SHORT_NAME { get; set; }
        public string PROCESS_IDENTIFIER { get; set; }
        public string STARTER_PATH { get; set; }
        public string STARTER_COMMAND { get; set; }
        public string VERSION { get; set; }
        public string COMMENT { get; set; }
        public Nullable<short> APPLICATION_TYPE_ID { get; set; }
        public string RECORD_CREATE_PERSON { get; set; }
        public Nullable<System.DateTime> RECORD_CREATE_DATE { get; set; }
        public string EXTRAREQUIREMENT { get; set; }
        public string EXTRAPOPUPMENU { get; set; }
        public Nullable<decimal> ISBASELINE { get; set; }
        public Nullable<decimal> IS64BIT { get; set; }
    
        public virtual ICollection<REL_OBJ_APP> REL_OBJ_APP { get; set; }
    }
}
