//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REGISTED_OBJECT
    {
        public T_REGISTED_OBJECT()
        {
            this.REL_OBJ_APP = new HashSet<REL_OBJ_APP>();
            this.T_TEST_STEPS = new HashSet<T_TEST_STEPS>();
        }
    
        public long OBJECT_ID { get; set; }
        public string OBJECT_HAPPY_NAME { get; set; }
        public Nullable<long> APPLICATION_ID { get; set; }
        public Nullable<long> TYPE_ID { get; set; }
        public string QUICK_ACCESS { get; set; }
        public string OBJECT_TYPE { get; set; }
        public string COMMENT { get; set; }
        public string ENUM_TYPE { get; set; }
        public Nullable<decimal> OBJECT_NAME_ID { get; set; }
        public Nullable<short> IS_CHECKERROR_OBJ { get; set; }
        public byte[] OBJ_DATA_SRC { get; set; }
    
        public virtual ICollection<REL_OBJ_APP> REL_OBJ_APP { get; set; }
        public virtual T_GUI_COMPONENT_TYPE_DIC T_GUI_COMPONENT_TYPE_DIC { get; set; }
        public virtual ICollection<T_TEST_STEPS> T_TEST_STEPS { get; set; }
    }
}
