//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_BATCH
    {
        public T_TEST_BATCH()
        {
            this.T_BAT_RESULT = new HashSet<T_BAT_RESULT>();
            this.T_TEST_BATCH_DETAIL = new HashSet<T_TEST_BATCH_DETAIL>();
        }
    
        public long BAT_ID { get; set; }
        public string BAT_NAME { get; set; }
        public string BAT_DESC { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
    
        public virtual ICollection<T_BAT_RESULT> T_BAT_RESULT { get; set; }
        public virtual ICollection<T_TEST_BATCH_DETAIL> T_TEST_BATCH_DETAIL { get; set; }
    }
}
