//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_SET
    {
        public long SETID { get; set; }
        public string SETNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CREATION_USER { get; set; }
        public string UPDATE_CREATION_USER { get; set; }
    }
}
