//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_CASE_VERSION
    {
        public long TC_VERSOIN_ID { get; set; }
        public Nullable<long> TEST_CASE_ID { get; set; }
        public string VERSION_NAME { get; set; }
        public string VERSION_DESC { get; set; }
        public Nullable<long> VERSION_NUMBER { get; set; }
        public Nullable<short> AVAILABLE_MARK { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<long> CREATOR_ID { get; set; }
    
        public virtual T_TEST_CASE_SUMMARY T_TEST_CASE_SUMMARY { get; set; }
    }
}
