//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_BATCH_DETAIL
    {
        public T_TEST_BATCH_DETAIL()
        {
            this.T_BAT_RESULT_DETAIL = new HashSet<T_BAT_RESULT_DETAIL>();
        }
    
        public long BAT_DTL_ID { get; set; }
        public long BAT_ID { get; set; }
        public long STORYOBARD_ID { get; set; }
        public string DTL_DESC { get; set; }
        public long RUN_ORDER { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
    
        public virtual ICollection<T_BAT_RESULT_DETAIL> T_BAT_RESULT_DETAIL { get; set; }
        public virtual T_TEST_BATCH T_TEST_BATCH { get; set; }
    }
}
