//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_ROLES
    {
        public decimal ROLE_ID { get; set; }
        public string ROLE_NAME { get; set; }
        public Nullable<short> ISACTIVE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<System.DateTime> CREATOR_DATE { get; set; }
    }
}
