//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TESTER_INFO
    {
        public T_TESTER_INFO()
        {
            this.T_USER_MAPPING = new HashSet<T_USER_MAPPING>();
        }
    
        public decimal TESTER_ID { get; set; }
        public string TESTER_NAME_LAST { get; set; }
        public string TESTER_NAME_M { get; set; }
        public string TESTER_NAME_F { get; set; }
        public string TESTER_LOGIN_NAME { get; set; }
        public string TESTER_PWD { get; set; }
        public Nullable<decimal> AVAILABLE_MARK { get; set; }
        public string TESTER_MAIL { get; set; }
        public string TESTER_NUMBER { get; set; }
        public decimal COMPANY_ID { get; set; }
        public string CREATOR_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string TESTER_DESC { get; set; }
    
        public virtual T_MARS_COMPANY T_MARS_COMPANY { get; set; }
        public virtual ICollection<T_USER_MAPPING> T_USER_MAPPING { get; set; }
    }
}
