//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_DATASETTAG
    {
        public long T_TEST_DATASETTAG_ID { get; set; }
        public Nullable<long> DATASETID { get; set; }
        public string GROUPID { get; set; }
        public string SETID { get; set; }
        public string FOLDERID { get; set; }
        public string EXPECTEDRESULTS { get; set; }
        public string STEPDESC { get; set; }
        public string DIARY { get; set; }
        public Nullable<long> SEQUENCE { get; set; }
    }
}
