//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TESTCASE_VERSION
    {
        public long TC_VERSION_ID { get; set; }
        public Nullable<long> TESTCASEID { get; set; }
        public Nullable<long> CREATORID { get; set; }
        public Nullable<short> ISAVAILABLE { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public long VERSIONID { get; set; }
    }
}
