//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_STEPS_TMP
    {
        public long STEPS_ID { get; set; }
        public Nullable<decimal> RUN_ORDER { get; set; }
        public Nullable<long> KEY_WORD_ID { get; set; }
        public Nullable<long> TEST_CASE_ID { get; set; }
        public Nullable<long> OBJECT_ID { get; set; }
        public string COLUMN_ROW_SETTING { get; set; }
        public string VALUE_SETTING { get; set; }
        public string COMMENT { get; set; }
        public Nullable<decimal> IS_RUNNABLE { get; set; }
    }
}
