//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_SUITE
    {
        public T_TEST_SUITE()
        {
            this.REL_TEST_CASE_TEST_SUITE = new HashSet<REL_TEST_CASE_TEST_SUITE>();
            this.REL_TEST_SUIT_PROJECT = new HashSet<REL_TEST_SUIT_PROJECT>();
            this.T_PROJ_TC_MGR = new HashSet<T_PROJ_TC_MGR>();
        }
    
        public long TEST_SUITE_ID { get; set; }
        public string TEST_SUITE_NAME { get; set; }
        public string TEST_SUITE_DESCRIPTION { get; set; }
    
        public virtual ICollection<REL_TEST_CASE_TEST_SUITE> REL_TEST_CASE_TEST_SUITE { get; set; }
        public virtual ICollection<REL_TEST_SUIT_PROJECT> REL_TEST_SUIT_PROJECT { get; set; }
        public virtual ICollection<T_PROJ_TC_MGR> T_PROJ_TC_MGR { get; set; }
    }
}
