//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_PRIVILEGE_ROLE_MAPPING
    {
        public decimal PRIVILEGE_ROLE_MAP_ID { get; set; }
        public decimal PRIVILEGE_ID { get; set; }
        public decimal ROLE_ID { get; set; }
        public short ISACTIVE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<System.DateTime> CREATOR_DATE { get; set; }
    }
}
