//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER_CONFIGURATION
    {
        public decimal USERCONFIGID { get; set; }
        public string MAINKEY { get; set; }
        public string SUBKEY { get; set; }
        public Nullable<decimal> USERID { get; set; }
        public byte[] BLOBVALUE { get; set; }
        public Nullable<short> BLOBVALUETYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYON { get; set; }
        public Nullable<short> ISDELETE { get; set; }
    }
}
