//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER_MAPPING
    {
        public decimal USER_MAPPING_ID { get; set; }
        public Nullable<decimal> TESTER_ID { get; set; }
        public string TEMP_KEY { get; set; }
        public Nullable<decimal> IS_DELETED { get; set; }
        public Nullable<decimal> STATUS { get; set; }
    
        public virtual T_TESTER_INFO T_TESTER_INFO { get; set; }
    }
}
