//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER_ACTIVEPAGE
    {
        public decimal ACTIVEPAGE_ID { get; set; }
        public decimal USER_ID { get; set; }
        public decimal PAGE_ID { get; set; }
        public string PAGE_NAME { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<decimal> PROJECT_ID { get; set; }
    }
}
