//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFEEDPROCESSDETAIL
    {
        public decimal FEEDPROCESSDETAILID { get; set; }
        public decimal FEEDPROCESSID { get; set; }
        public string FILENAME { get; set; }
        public string FEEDPROCESSSTATUS { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string FILETYPE { get; set; }
    }
}
