//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLOGREPORT
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CREATIONDATE { get; set; }
        public string MESSAGETYPE { get; set; }
        public string ACTION { get; set; }
        public string CELLADDRESS { get; set; }
        public string VALIDATIONNAME { get; set; }
        public string VALIDATIONDESCRIPTION { get; set; }
        public string APPLICATIONNAME { get; set; }
        public string TESTCASENAME { get; set; }
        public string DATASETNAME { get; set; }
        public string TESTSTEPNUMBER { get; set; }
        public string OBJECTNAME { get; set; }
        public string COMMENTDATA { get; set; }
        public string ERRORDESCRIPTION { get; set; }
        public string PROGRAMLOCATION { get; set; }
        public Nullable<decimal> FEEDPROCESSINGDETAILSID { get; set; }
        public Nullable<decimal> FEEDPROCESSID { get; set; }
        public string GENERAL { get; set; }
        public string PROJECTNAME { get; set; }
        public string STORYBOARDNAME { get; set; }
        public string TESTSUITE { get; set; }
        public string DEPENDENCY { get; set; }
        public string RUNORDER { get; set; }
    }
}
