//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_DATA_SETTING_TST
    {
        public long DATA_SETTING_ID { get; set; }
        public long STEPS_ID { get; set; }
        public Nullable<decimal> LOOP_ID { get; set; }
        public string DATA_VALUE { get; set; }
        public Nullable<short> VALUE_OR_OBJECT { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> DATA_SUMMARY_ID { get; set; }
        public Nullable<short> DATA_DIRECTION { get; set; }
        public Nullable<long> VERSION { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<long> POOL_ID { get; set; }
    }
}
