//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_PROJECT_VIEW
    {
        public string PROJECT_NAME { get; set; }
        public long PROJECT_ID { get; set; }
        public string TEST_SUITE_NAME { get; set; }
        public long TEST_SUITE_ID { get; set; }
        public string APP_SHORT_NAME { get; set; }
        public long APPLICATION_ID { get; set; }
    }
}
