//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_CASE_VIEW
    {
        public string PROJECT_NAME { get; set; }
        public string TEST_SUITE_NAME { get; set; }
        public string TEST_CASE_NAME { get; set; }
        public string KEY_WORD_NAME { get; set; }
        public long OBJECT_ID { get; set; }
        public string OBJECT_HAPPY_NAME { get; set; }
        public string COLUMN_ROW_SETTING { get; set; }
        public string DATA_VALUE { get; set; }
        public Nullable<decimal> LOOP_ID { get; set; }
    }
}
