//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OBJECT_SNAPSHOT
    {
        public decimal OBJECT_NAME_ID { get; set; }
        public string OBJECT_HAPPY_NAME { get; set; }
        public string COMMENT { get; set; }
        public Nullable<long> APPLICATION_ID { get; set; }
        public string ENUM_TYPE { get; set; }
        public long OBJECT_ID { get; set; }
        public string OBJECT_TYPE { get; set; }
        public string QUICK_ACCESS { get; set; }
        public Nullable<long> TYPE_ID { get; set; }
        public Nullable<short> IS_CHECKERROR_OBJ { get; set; }
        public string TYPE_NAME { get; set; }
        public string PEG_NAME { get; set; }
        public string PEG_QUICK_ACCESS { get; set; }
        public long PEG_ID { get; set; }
    }
}
