//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STB_PROJ_APP_FULLVISION
    {
        public Nullable<long> PROJECT_ID { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<long> CREATER { get; set; }
        public string DESCRIPTION { get; set; }
        public long STORYBOARD_ID { get; set; }
        public string STORYBOARD_NAME { get; set; }
        public Nullable<long> APPLICATION_ID { get; set; }
        public string APP_SHORT_NAME { get; set; }
        public Nullable<short> APPLICATION_TYPE_ID { get; set; }
    }
}
