//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_STORYBOARD_TEST_FULLVISION
    {
        public long STORYBOARD_ID { get; set; }
        public Nullable<decimal> STORYBOARD_DETAIL_ID { get; set; }
        public string STORYBOARD_NAME { get; set; }
        public Nullable<decimal> PROJECT_ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public string PROJECT_DESCRIPTION { get; set; }
        public string TEST_CASE_NAME { get; set; }
        public Nullable<decimal> TEST_CASE_ID { get; set; }
        public string TEST_STEP_DESCRIPTION { get; set; }
        public Nullable<decimal> TEST_SUITE_ID { get; set; }
        public string TEST_SUITE_NAME { get; set; }
        public string TEST_SUITE_DESCRIPTION { get; set; }
        public Nullable<decimal> RUN_ORDER { get; set; }
        public Nullable<long> DEPENDS_ON { get; set; }
        public string ALIAS_NAME { get; set; }
        public string PARENT_ALIAS_NAME { get; set; }
        public string DISPLAY_NAME { get; set; }
        public Nullable<short> TEST_RUN_VALUE { get; set; }
        public Nullable<long> LATEST_TEST_MARK_ID { get; set; }
        public Nullable<long> HIST_LATEST_TEST_MARK_ID { get; set; }
        public Nullable<long> HIST_ID { get; set; }
        public Nullable<long> HIST_TEST_ID { get; set; }
        public Nullable<System.DateTime> TEST_CASE_BEGIN_TIME { get; set; }
        public Nullable<System.DateTime> TEST_CASE_END_TIME { get; set; }
        public string HIST_TEST_RESULT_IN_TEXT { get; set; }
        public Nullable<decimal> HIST_TEST_MODE { get; set; }
        public Nullable<short> HIST_RESULT { get; set; }
        public Nullable<long> DATA_SETTING_ID { get; set; }
        public Nullable<long> DATA_SUMMARY_ID { get; set; }
        public Nullable<System.DateTime> DATA_SET_CREATETIME { get; set; }
        public Nullable<long> DATA_SET_TESTERID { get; set; }
        public Nullable<long> DATA_SET_VERSION { get; set; }
        public string DATA_SET_ALIAS_NAME { get; set; }
        public Nullable<short> DATA_SET_SHARE_MARK { get; set; }
        public Nullable<short> DATA_SET_STATUS { get; set; }
        public Nullable<short> DATA_SET_TYPE { get; set; }
        public string DATASET_DESCRIPTION { get; set; }
    }
}
