//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TEST_DATARPT_CAPTURE
    {
        public string KEY_WORD_NAME { get; set; }
        public string OBJECT_HAPPY_NAME { get; set; }
        public string INPUT_VALUE_SETTING { get; set; }
        public string RETURN_VALUES { get; set; }
        public string ACTUAL_INPUT_DATA { get; set; }
        public Nullable<long> LATEST_TEST_MARK_ID { get; set; }
        public Nullable<long> STORYBOARD_DETAIL_ID { get; set; }
        public Nullable<decimal> LOOP_ID { get; set; }
        public Nullable<decimal> RUN_ORDER { get; set; }
        public Nullable<short> TEST_MODE { get; set; }
        public long TEST_REPORT_STEP_ID { get; set; }
        public Nullable<long> STORYBOARD_ID { get; set; }
    }
}
