---MarsIE Tables and sequences

  
  CREATE TABLE "ELSEORDER" 
   (	"ID" NUMBER(*,0), 
	"ELSESTEPID" NUMBER(*,0), 
	"PEGWINDOWSTEPID" NUMBER(*,0), 
	"TESTCASENAME" VARCHAR2(200 BYTE), 
	"FEEDPROCESSDETAILSID" NUMBER(*,0)
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
/

  CREATE TABLE "ErrorLog" 
   (	"ErrorLogId" NUMBER NOT NULL ENABLE, 
	"ExceptionMessage" VARCHAR2(500 BYTE), 
	"ControllerName" VARCHAR2(500 BYTE), 
	"ExceptionStackTrace" VARCHAR2(500 BYTE), 
	"LogTime" DATE, 
	"CreatedBy" VARCHAR2(500 BYTE), 
	"URL" VARCHAR2(500 BYTE), 
	"UrlReferrer" VARCHAR2(500 BYTE), 
	"UserAgent" VARCHAR2(500 BYTE), 
	"UserHostAddress" VARCHAR2(500 BYTE), 
	"UserHostName" VARCHAR2(500 BYTE), 
	 CONSTRAINT "ErrorLog_PK" PRIMARY KEY ("ErrorLogId")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
/

  CREATE TABLE "IFENDORDER" 
   (	"ID" NUMBER(*,0), 
	"IFSTEPID" NUMBER(*,0), 
	"ELSESTEPID" NUMBER(*,0), 
	"IFENDSTEPID" NUMBER(*,0), 
	"PEGWINDOWSTEPID" NUMBER(*,0), 
	"TESTCASENAME" VARCHAR2(200 BYTE), 
	"FEEDPROCESSDETAILSID" NUMBER(*,0)
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
/

  CREATE TABLE "IFORDER" 
   (	"ID" NUMBER(*,0), 
	"IFSTEPID" NUMBER(*,0), 
	"PEGWINDOWSTEPID" NUMBER(*,0), 
	"TESTCASENAME" VARCHAR2(200 BYTE), 
	"FEEDPROCESSDETAILSID" NUMBER(*,0)
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
/

  CREATE TABLE "LOGREPORT" 
   (	"FILENAME" VARCHAR2(500 BYTE), 
	"OBJECT" VARCHAR2(500 BYTE), 
	"STATUS" VARCHAR2(500 BYTE), 
	"LOGDETAILS" CLOB, 
	"ID" NUMBER NOT NULL ENABLE, 
	"CREATEDON" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"FEEDPROCESSDETAILID" NUMBER, 
	 CONSTRAINT "LOGREPORT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   
 LOB ("LOGDETAILS") STORE AS SECUREFILE (
   ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
/

  CREATE TABLE "OBJECTS_DUPLICATE" 
   (	"OBJECT_NAME_ID" NUMBER(*,0), 
	"OBEJCT_HAPPY_NAME" VARCHAR2(1000 BYTE)
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
/

  CREATE TABLE "OBJECTS_ORIGINAL" 
   (	"OBJECT_NAME_ID" NUMBER(*,0), 
	"OBEJCT_HAPPY_NAME" VARCHAR2(1000 BYTE)
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
/

  CREATE TABLE "PEGWINODWORDER" 
   (	"ID" NUMBER(*,0), 
	"PEGWINDOW" NUMBER(*,0), 
	"TESTCASENAME" VARCHAR2(200 BYTE), 
	"FEEDPROCESSDETAILSID" NUMBER(*,0)
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
/

  CREATE GLOBAL TEMPORARY TABLE "STORYBOARD_INSERT_TEMP" 
   (	"NAME" VARCHAR2(200 BYTE), 
	"TYPE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE)
   ) ON COMMIT DELETE ROWS ;

/

  CREATE GLOBAL TEMPORARY TABLE "STORYBOARD_TEMP" 
   (	"NAME" VARCHAR2(200 BYTE), 
	"TYPE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"STORYBOARDNAME" VARCHAR2(200 BYTE)
   ) ON COMMIT DELETE ROWS ;
/

  CREATE TABLE "TBLFEEDPROCESS" 
   (	"FEEDPROCESSID" NUMBER NOT NULL ENABLE, 
	"FEEDPROCESSSTATUS" VARCHAR2(500 BYTE), 
	"FEEDRUNON" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATEDBY" VARCHAR2(500 BYTE), 
	"CREATEDON" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT "TBLFEEDPROCESS_PK" PRIMARY KEY ("FEEDPROCESSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

  CREATE OR REPLACE  TRIGGER "TBLFEEDPROCESS_TRG" 
BEFORE INSERT ON TBLFEEDPROCESS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "TBLFEEDPROCESS_TRG" ENABLE;
/

  CREATE TABLE "TBLFEEDPROCESSDETAILS" 
   (	"FEEDPROCESSDETAILID" NUMBER NOT NULL ENABLE, 
	"FEEDPROCESSID" NUMBER NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(500 BYTE), 
	"FEEDPROCESSSTATUS" VARCHAR2(500 BYTE), 
	"CREATEDBY" VARCHAR2(500 BYTE), 
	"CREATEDON" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"FILETYPE" VARCHAR2(500 BYTE), 
	 CONSTRAINT "TBLFEEDPROCESSDETAILS_PK" PRIMARY KEY ("FEEDPROCESSDETAILID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

  CREATE OR REPLACE  TRIGGER "TBLFEEDPROCESSDETAILS_TRG" 
BEFORE INSERT ON TBLFEEDPROCESSDETAILS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "TBLFEEDPROCESSDETAILS_TRG" ENABLE;
/

  CREATE TABLE "TBLLOGREPORT" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CREATIONDATE" TIMESTAMP (6), 
	"MESSAGETYPE" VARCHAR2(500 BYTE), 
	"ACTION" VARCHAR2(500 BYTE), 
	"CELLADDRESS" VARCHAR2(500 BYTE), 
	"VALIDATIONNAME" VARCHAR2(500 BYTE), 
	"VALIDATIONDESCRIPTION" VARCHAR2(500 BYTE), 
	"APPLICATIONNAME" VARCHAR2(500 BYTE), 
	"TESTCASENAME" VARCHAR2(500 BYTE), 
	"DATASETNAME" VARCHAR2(500 BYTE), 
	"TESTSTEPNUMBER" VARCHAR2(500 BYTE), 
	"OBJECTNAME" VARCHAR2(500 BYTE), 
	"COMMENTDATA" VARCHAR2(500 BYTE), 
	"ERRORDESCRIPTION" VARCHAR2(500 BYTE), 
	"PROGRAMLOCATION" VARCHAR2(500 BYTE), 
	"FEEDPROCESSINGDETAILSID" NUMBER, 
	"FEEDPROCESSID" NUMBER(*,0), 
	"GENERAL" VARCHAR2(500 BYTE), 
	"PROJECTNAME" VARCHAR2(500 BYTE), 
	"STORYBOARDNAME" VARCHAR2(200 BYTE), 
	"TESTSUITE" VARCHAR2(200 BYTE), 
	"DEPENDENCY" VARCHAR2(200 BYTE), 
	"RUNORDER" VARCHAR2(200 BYTE)
   )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

  CREATE UNIQUE INDEX "TBLLOGREPROT_PK" ON "TBLLOGREPORT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

  CREATE OR REPLACE  TRIGGER "TBLLOGREPORT_TRG" 
BEFORE INSERT ON TBLLOGREPORT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TBLLOGREPORT_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "TBLLOGREPORT_TRG" ENABLE;
/

  CREATE TABLE "TBLSTGCOMPAREPARAM" 
   (	"DATASOURCENAME" VARCHAR2(500 BYTE), 
	"DATASOURCETYPE" VARCHAR2(500 BYTE), 
	"FEEDPROCESSDETAILID" NUMBER, 
	"DETAILS" CLOB, 
	"ID" NUMBER, 
	"CREATEDON" TIMESTAMP (6) WITH LOCAL TIME ZONE
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
   
 LOB ("DETAILS") STORE AS SECUREFILE (
   ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

  CREATE UNIQUE INDEX "TBLSTGCOMPAREPARAM_PK" ON "TBLSTGCOMPAREPARAM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;
/

  CREATE TABLE "TBLSTGGUIOBJECT" 
   (	"OBJECTNAME" VARCHAR2(500 BYTE), 
	"TYPE" VARCHAR2(500 BYTE), 
	"QUICKACCESS" VARCHAR2(500 BYTE), 
	"PARENT" VARCHAR2(500 BYTE), 
	"OBJECTCOMMENT" VARCHAR2(500 BYTE), 
	"ENUMTYPE" VARCHAR2(500 BYTE), 
	"SQL" VARCHAR2(500 BYTE), 
	"APPLICATIONNAME" VARCHAR2(500 BYTE), 
	"FEEDPROCESSDETAILID" NUMBER NOT NULL ENABLE, 
	"ID" NUMBER NOT NULL ENABLE, 
	"CREATEDON" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT "TBLSTGGUIOBJECT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   )
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
/

  CREATE TABLE "TBLSTGSTORYBOARD" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FEEDPROCESSDETAILID" NUMBER NOT NULL ENABLE, 
	"TABNAME" VARCHAR2(500 BYTE), 
	"RUNORDER" NUMBER, 
	"APPLICATIONNAME" VARCHAR2(500 BYTE), 
	"PROJECTNAME" VARCHAR2(500 BYTE), 
	"PROJECTDETAIL" VARCHAR2(500 BYTE), 
	"STORYBOARDNAME" VARCHAR2(500 BYTE), 
	"ACTIONNAME" VARCHAR2(500 BYTE), 
	"STEPNAME" VARCHAR2(500 BYTE), 
	"SUITENAME" VARCHAR2(500 BYTE), 
	"CASENAME" VARCHAR2(500 BYTE), 
	"DATASETNAME" VARCHAR2(500 BYTE), 
	"DEPENDENCY" VARCHAR2(500 BYTE), 
	"CREATEDDATE" DATE, 
	"DEPENDENCYID" NUMBER, 
	 CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

/

  CREATE TABLE "TBLSTGTESTCASE" 
   (	"TESTSUITENAME" VARCHAR2(500 BYTE), 
	"TESTCASENAME" VARCHAR2(500 BYTE), 
	"TESTCASEDESCRIPTION" VARCHAR2(500 BYTE), 
	"DATASETMODE" VARCHAR2(500 BYTE), 
	"KEYWORD" VARCHAR2(500 BYTE), 
	"OBJECT" VARCHAR2(500 BYTE), 
	"PARAMETER" VARCHAR2(500 BYTE), 
	"COMMENTS" VARCHAR2(500 BYTE), 
	"DATASETNAME" VARCHAR2(500 BYTE), 
	"DATASETVALUE" VARCHAR2(500 BYTE), 
	"ROWNUMBER" NUMBER, 
	"FEEDPROCESSDETAILID" NUMBER, 
	"TABNAME" VARCHAR2(500 BYTE), 
	"APPLICATION" VARCHAR2(500 BYTE), 
	"ID" NUMBER, 
	"CREATEDON" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"SKIP" NUMBER(*,0), 
	"DATASETDESCRIPTION" VARCHAR2(500 BYTE)
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
/

  CREATE TABLE "TBLSTGVARIABLE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FEEDPROCESSDETAILID" NUMBER, 
	"NAME" VARCHAR2(200 BYTE), 
	"VALUE" CLOB, 
	"TYPE" VARCHAR2(200 BYTE), 
	"BASE_COMP" VARCHAR2(200 BYTE), 
	"CREATEDDATE" DATE, 
	"BASE_COMP_ID" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   
 LOB ("VALUE") STORE AS SECUREFILE (
   ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
/


  CREATE TABLE "TEMP1" 
   (	"TESTCASENAME" VARCHAR2(500 BYTE), 
	"DATASETNAME" VARCHAR2(500 BYTE), 
	"COUNTOFROW" NUMBER(*,0)
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
/

  CREATE TABLE "TEMPALL" 
   (	"TESTSUITNAME" VARCHAR2(100 BYTE), 
	"TESTCASENAME" VARCHAR2(100 BYTE), 
	"APPLICATION" VARCHAR2(100 BYTE)
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
   ;
/

  CREATE TABLE "TEMPDWTESTCASE" 
   (	"TESTCASENAME" VARCHAR2(500 BYTE), 
	"DATASETNAME" VARCHAR2(500 BYTE), 
	"KEYWORDNAME" VARCHAR2(500 BYTE), 
	"OBJECTNAME" VARCHAR2(500 BYTE), 
	"ORDERNUMBER" NUMBER(*,0)
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

/

  CREATE TABLE "TEMPFALSEAPPLICATION" 
   (	"TESTSUITNAME" VARCHAR2(200 BYTE), 
	"TESTCASENAME" VARCHAR2(200 BYTE), 
	"APPLICATION" VARCHAR2(200 BYTE), 
	"FLAG" NUMBER(*,0)
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
/

  CREATE TABLE "TEMPSTGTESTCASE" 
   (	"TESTCASENAME" VARCHAR2(500 BYTE), 
	"DATASETNAME" VARCHAR2(500 BYTE), 
	"KEYWORDNAME" VARCHAR2(500 BYTE), 
	"OBJECTNAME" VARCHAR2(500 BYTE), 
	"ORDERNUMBER" NUMBER(*,0)
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
/

  CREATE TABLE "TMP_T_OBJ" 
   (	"OBJECT_ID" NUMBER(16,0) NOT NULL ENABLE, 
	"APPLICATION_ID" NUMBER(16,0), 
	"TYPE_ID" NUMBER(16,0), 
	"QUICK_ACCESS" VARCHAR2(512 BYTE), 
	"OBJECT_TYPE" VARCHAR2(32 CHAR), 
	"COMMENT" VARCHAR2(128 BYTE), 
	"ENUM_TYPE" VARCHAR2(100 BYTE), 
	"OBJECT_NAME_ID" NUMBER, 
	"OBJECT_HAPPY_NAME" VARCHAR2(255 CHAR), 
	"OBJ_DATA_SRC" BLOB, 
	"IS_CHECKERROR_OBJ" NUMBER(2,0), 
	"OLD_OBJID" NUMBER(16,0) NOT NULL ENABLE
   ) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   
 LOB ("OBJ_DATA_SRC") STORE AS SECUREFILE (
   ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
/

  CREATE TABLE "TBLMESSAGE" 
   (	"ID" NUMBER, 
	"MESSAGESYMBOL" VARCHAR2(500 BYTE), 
	"MESSAGE" VARCHAR2(500 BYTE)
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

  CREATE UNIQUE INDEX "TBLMESSAGE_PK" ON "TBLMESSAGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;


---Sequences---

   CREATE SEQUENCE  "LOGREPORT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 62101 CACHE 20 NOORDER  NOCYCLE  ;
/

   


   CREATE SEQUENCE  "TBLFEEDPROCESS_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1060 CACHE 20 NOORDER  NOCYCLE  ;
/

   CREATE SEQUENCE  "TBLFEEDPROCESSDETAILS_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1040 CACHE 20 NOORDER  NOCYCLE   ;
/

   CREATE SEQUENCE  "TBLLOGREPORT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 57501 CACHE 20 NOORDER  NOCYCLE  ;
/

   CREATE SEQUENCE  "TBLMESSAGE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 83 NOCACHE  NOORDER  NOCYCLE    ;
/

   CREATE SEQUENCE  "TBLSTGSTORYBOARD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 20000 CACHE 20 NOORDER  NOCYCLE  ;
/

   CREATE SEQUENCE  "TBLSTGTESTCASE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 488110 CACHE 20 NOORDER  NOCYCLE  ;
/

   CREATE SEQUENCE  "TEMP1_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1161 CACHE 20 NOORDER  NOCYCLE   ;
/

   CREATE SEQUENCE  "TEMPDWTESTCASE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 941 CACHE 20 NOORDER  NOCYCLE ;
/

   CREATE SEQUENCE  "TEMPSTGTESTCASE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 941 CACHE 20 NOORDER  NOCYCLE  ;
/

---Insert into tblmessage
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (9,'INFO-SKIP','Dataset is Skipped');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (10,'INFO-DELETE-WAREHOUSE','Dataset is deleted from MARS database');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (13,'ERR-AFTER-ORDER-MATCH','After Order Match, Step ID not found');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (18,'ERR-APP-NOTEXISTS','One of the Application given in the Testcase does not exist in the Database');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (12,'ERR-APPLICATION','Application Name is not is in MARS database');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (14,'ERR-IN-MODE-D-TESTCASE','Testcase not found in Database');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (15,'ERR-IN-MODE-D-DATASET','Dataset not found in Database');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (16,'ERR-IN-MODE-D-TESTCASE-DATASET','Testcase and Dataset not found in Database');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (17,'LOGRECORD-DATASET-REMOVE','LOGRECORD OF DATASET WHICH REMOVE');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (19,'ERR-IN-OVERWRIGHT-TESTCASE','TESTCASE IS NOT FOUND IN DATAWAREHOUSE');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (20,'INFO-DELETE-WAREHOUSE-OVERWRITE','Testcase is deleted from the database');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (1,'ERR-TYPE','Keyword not found in System');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (2,'ERR-APP','Application ID is Invalid');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (3,'ERR-DATA-SRC-TYPE','Data Source Type is Invalid');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (4,'SUCC-INFO','Data inserted successfully');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (5,'ERR-OBJ','Object not in table');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (6,'ERR-COUNT','No match found, Error in count');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (7,'ERR-WAREHOUSE-STAGING-COUNT','Count of steps in spreadsheet and Count of steps in MARS are not matching.');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (8,'ERR-WAREHOUSE-STAGING-ORDER','Object Keyword Order for test case is not matching with database');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (11,'ERR-SUITENAME','Suite name is different');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (21,'OBJECT-PEGWINDOW-CHECKING','Parent PegWindow not found');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (26,'OBJECT-APPLICATION-LINKING','Object is not linked with one of the application');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (27,'DUPLICATE_DATASET','Multiple Dataset with same name are not allowed.');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (28,'MULTIPLE-TESTSUITE','Multiple Testsuites found in the Import. Spreadsheet should have only one Testsuite');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (22,'OBJECT-KEYWORD-LINKING','Invalid Object for Keyword');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (23,'ORDER-OBJECT-INVALID	ORDER','Pegwindow Object Order is Invalid');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (24,'RELATION-OBJECT-PGEWINDOW-INVALID','Object does not belong to Parent PegWindow');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (25,'IF ELSE ORDER','IF-ELSE-IFEND in incorrect order');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (29,'OBJECT TYPE INVALID','OBJECT TYPE ID IS INVALID');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (42,'Global_Variable_Name_Type_Duplicate','Global Variable Duplicate');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (43,'Modal_Loop_Variable_Name_Type_Base_Comp_Duplicate','Modal/Loop Variable Duplicate');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (44,'Global_Exit_In_Modal_Loop','Insert Global variable Exit in Modal/Loop Variable');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (45,'Modal_Loop_Exit_In_Modal_Loop','Insert Modal/Loop Variable Exit in Global Variable');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (46,'Global_Modal_Loop_Duplicate_Name','Global , Modal/Loop Variable name duplicate');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (47,'Global_Base_Comp_Validation','Global Variable has not Baseline/Compare value');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (51,'ApplictionName-Import-Different','ApplicationName Differet in Import sheet');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (52,'ProjectName-Import-Different','ProjectName Differet in Import sheet');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (82,'Repeat_Storyboard_Spreadsheet','StoryboardName repeated in Spreadsheets');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (30,'ERR-APP-SB','Application not found in System');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (31,'ERR-PRJ-SB','Project not found in System');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (32,'ERR-STORYBOARD-SB','Story board name does not exist');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (33,'ERR-SUITENAME-SB','Test Suite not found in System');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (34,'ERR-TESTCASE-SB','Test Case not found in System');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (35,'ERR-DATASET-SB','Data Set not found in System');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (36,'ERR-DEPENDENT-STEPNAME-SB','Dependency name does not valid');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (37,'TESTSUITE-PROJECT-LINKING-SB','Test Suite is not linked with project');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (38,'TESTCASE-TESTSUITE-LINKING-SB','Test Case is not linked with test Suit');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (39,'DATASET-TESTCASE-LINKING-SB','DataSet is not linked with test Case');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (40,'DUP-STORYBOARD-STEPNAME','Duplicate stepname not allow for storyboard');
Insert into TBLMESSAGE (ID,MESSAGESYMBOL,MESSAGE) values (41,'DATASET-STORYBOARD-LINKING-SB','DataSet is not linked with storyboard');
/
