//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACUP
    {
        public string BR { get; set; }
        public string PRODUCT { get; set; }
        public string TYPE { get; set; }
        public string ARGNO { get; set; }
        public string DEALNO { get; set; }
        public string SEQ { get; set; }
        public string GLNO { get; set; }
        public string COSTCENT { get; set; }
        public string CCY { get; set; }
        public string BEIND { get; set; }
        public string CODE { get; set; }
        public string QUAL { get; set; }
        public string EFFDATE { get; set; }
        public string POSTDATE { get; set; }
        public string CMNE { get; set; }
        public string DRCRIND { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string SMEANS { get; set; }
        public string SACCT { get; set; }
        public string DESCR { get; set; }
    }
}
