//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MV_LAST_TC_INFO
    {
        public long HIST_ID { get; set; }
        public Nullable<long> TEST_CASE_ID { get; set; }
        public Nullable<long> STORYBOARD_DETAIL_ID { get; set; }
        public Nullable<System.DateTime> TEST_BEGIN_TIME { get; set; }
        public Nullable<System.DateTime> TEST_END_TIME { get; set; }
        public string TEST_RESULT_IN_TEXT { get; set; }
        public Nullable<short> TEST_MODE { get; set; }
        public Nullable<short> TEST_RESULT { get; set; }
        public Nullable<long> TESTER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<long> LATEST_TEST_MARK_ID { get; set; }
        public Nullable<long> RELY_TEST_CASE_ID { get; set; }
        public string RESULT_ALIAS_NAME { get; set; }
        public string RESULT_DESC { get; set; }
    }
}
