//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MV_TC_DATASUMMARY
    {
        public string ALIAS_NAME { get; set; }
        public long DATA_SUMMARY_ID { get; set; }
        public Nullable<long> TEST_CASE_ID { get; set; }
        public Nullable<short> AVAILABLE_MARK { get; set; }
        public Nullable<long> DATA_VERSION { get; set; }
        public Nullable<short> DATA_STATUS { get; set; }
        public Nullable<short> DATA_SET_TYPE { get; set; }
        public string DATASET_DESCRIPTION { get; set; }
    }
}
