//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_TEST_CASE_TEST_SUITE
    {
        public long RELATIONSHIP_ID { get; set; }
        public Nullable<long> TEST_CASE_ID { get; set; }
        public Nullable<long> TEST_SUITE_ID { get; set; }
    
        public virtual T_TEST_SUITE T_TEST_SUITE { get; set; }
        public virtual T_TEST_CASE_SUMMARY T_TEST_CASE_SUMMARY { get; set; }
    }
}
