//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_APP_PROJ
    {
        public long RELATIONSHIP_ID { get; set; }
        public Nullable<long> APPLICATION_ID { get; set; }
        public Nullable<long> PROJECT_ID { get; set; }
    
        public virtual T_TEST_PROJECT T_TEST_PROJECT { get; set; }
    }
}
