//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BASELINE_DATA_DETAIL
    {
        public decimal DETAIL_ID { get; set; }
        public Nullable<decimal> DATA_BASE_OBJ_ID { get; set; }
        public Nullable<int> LOOP_ID { get; set; }
        public string DATA_VALUE { get; set; }
    
        public virtual T_BASELINE_DATA_SUMMARY T_BASELINE_DATA_SUMMARY { get; set; }
    }
}
