//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COMPARE_CONFIG
    {
        public decimal COMPARE_ID { get; set; }
        public string COMPARE_NAME { get; set; }
        public string S1_TYPE { get; set; }
        public string S1_DBCONN { get; set; }
        public string S1_QUERY { get; set; }
        public string S1_FILE_LOC { get; set; }
        public string S2_TYPE { get; set; }
        public string S2_DBCONN { get; set; }
        public string S2_QUERY { get; set; }
        public string S2_FILE_LOC { get; set; }
        public string O_FILE_LOC { get; set; }
        public string KEY_FIELDS { get; set; }
        public string SHOW_FIELDS { get; set; }
        public string COMPARE_FIELDS { get; set; }
        public string ROW_FIELDS { get; set; }
        public string COLUMN_FIELDS { get; set; }
    }
}
