//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COMPARE_QUERIES
    {
        public decimal QUERY_ID { get; set; }
        public string QUERY_NAME { get; set; }
        public string QUERY_VAL { get; set; }
    }
}
