//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DATA_SOURCE_TEST
    {
        public long DATA_SOURCE_ID { get; set; }
        public string DATA_SOURCE_NAME { get; set; }
        public Nullable<short> DATA_SOURCE_TYPE { get; set; }
        public string DETAILS { get; set; }
        public string DB_CONNECTION { get; set; }
        public Nullable<short> DB_TYPE { get; set; }
        public string TEST_CONNECTION { get; set; }
    }
}
