//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DIC_RELATION_KEYWORD
    {
        public long RELATION_ID { get; set; }
        public Nullable<long> TYPE_ID { get; set; }
        public Nullable<long> KEY_WORD_ID { get; set; }
    
        public virtual T_GUI_COMPONENT_TYPE_DIC T_GUI_COMPONENT_TYPE_DIC { get; set; }
        public virtual T_KEYWORD T_KEYWORD { get; set; }
    }
}
