//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_KEYWORD
    {
        public T_KEYWORD()
        {
            this.T_DIC_RELATION_KEYWORD = new HashSet<T_DIC_RELATION_KEYWORD>();
            this.T_TEST_STEPS = new HashSet<T_TEST_STEPS>();
        }
    
        public long KEY_WORD_ID { get; set; }
        public string KEY_WORD_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<short> KEY_WORD_POSITION_ID { get; set; }
        public string ENTRY_IN_DATA_FILE { get; set; }
    
        public virtual ICollection<T_DIC_RELATION_KEYWORD> T_DIC_RELATION_KEYWORD { get; set; }
        public virtual ICollection<T_TEST_STEPS> T_TEST_STEPS { get; set; }
    }
}
