//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MARS_COMPANY
    {
        public T_MARS_COMPANY()
        {
            this.T_TESTER_INFO = new HashSet<T_TESTER_INFO>();
        }
    
        public decimal COMPANY_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_DESC { get; set; }
        public string COMPANY_NUMBER { get; set; }
        public string COMPANY_ADDRESS { get; set; }
        public string CREATE_USERNAME { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<decimal> AVAILABLE_MARK { get; set; }
    
        public virtual ICollection<T_TESTER_INFO> T_TESTER_INFO { get; set; }
    }
}
