//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OBJECT_NAMEINFO
    {
        public decimal OBJECT_NAME_ID { get; set; }
        public string OBJECT_HAPPY_NAME { get; set; }
        public Nullable<short> PEGWINDOW_MARK { get; set; }
        public string OBJNAME_DESCRIPTION { get; set; }
        public Nullable<decimal> EXT_ID { get; set; }
    }
}
