//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PROJ_TC_MGR
    {
        public T_PROJ_TC_MGR()
        {
            this.T_STORYBOARD_DATASET_SETTING = new HashSet<T_STORYBOARD_DATASET_SETTING>();
        }
    
        public long STORYBOARD_DETAIL_ID { get; set; }
        public Nullable<long> PROJECT_ID { get; set; }
        public Nullable<long> TEST_CASE_ID { get; set; }
        public Nullable<long> STORYBOARD_ID { get; set; }
        public Nullable<short> RUN_TYPE { get; set; }
        public Nullable<long> DEPENDS_ON { get; set; }
        public Nullable<long> RUN_ORDER { get; set; }
        public Nullable<long> LATEST_TEST_MARK_ID { get; set; }
        public Nullable<decimal> RECORD_VERSION { get; set; }
        public string ALIAS_NAME { get; set; }
        public Nullable<long> TEST_SUITE_ID { get; set; }
    
        public virtual T_TEST_SUITE T_TEST_SUITE { get; set; }
        public virtual T_STORYBOARD_SUMMARY T_STORYBOARD_SUMMARY { get; set; }
        public virtual T_TEST_CASE_SUMMARY T_TEST_CASE_SUMMARY { get; set; }
        public virtual T_TEST_PROJECT T_TEST_PROJECT { get; set; }
        public virtual ICollection<T_STORYBOARD_DATASET_SETTING> T_STORYBOARD_DATASET_SETTING { get; set; }
    }
}
