//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_STORYBOARD_HISTORY
    {
        public long DASHBOARD_HIST_ID { get; set; }
        public Nullable<long> STORYBOARD_ID { get; set; }
        public Nullable<long> VERION { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<long> CREATOR { get; set; }
        public string STORYBOARD_NAME { get; set; }
        public Nullable<long> ASSIGNED_PROJECT_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> HISTORY_CREATE_TIME { get; set; }
        public string REASON { get; set; }
    
        public virtual T_STORYBOARD_SUMMARY T_STORYBOARD_SUMMARY { get; set; }
    }
}
