//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_STORYBOARD_SUMMARY
    {
        public T_STORYBOARD_SUMMARY()
        {
            this.T_PROJ_TC_MGR = new HashSet<T_PROJ_TC_MGR>();
            this.T_STORYBOARD_HISTORY = new HashSet<T_STORYBOARD_HISTORY>();
        }
    
        public long STORYBOARD_ID { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<decimal> LATEST_VERISON { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> CREATER { get; set; }
        public Nullable<long> ASSIGNED_PROJECT_ID { get; set; }
        public string STORYBOARD_NAME { get; set; }
    
        public virtual ICollection<T_PROJ_TC_MGR> T_PROJ_TC_MGR { get; set; }
        public virtual ICollection<T_STORYBOARD_HISTORY> T_STORYBOARD_HISTORY { get; set; }
    }
}
