//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_PROJECT
    {
        public T_TEST_PROJECT()
        {
            this.REL_APP_PROJ = new HashSet<REL_APP_PROJ>();
            this.REL_TEST_SUIT_PROJECT = new HashSet<REL_TEST_SUIT_PROJECT>();
            this.T_PROJ_TC_MGR = new HashSet<T_PROJ_TC_MGR>();
            this.T_PROJECT_DATA_SOURCE = new HashSet<T_PROJECT_DATA_SOURCE>();
        }
    
        public long PROJECT_ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public string PROJECT_DESCRIPTION { get; set; }
        public string CREATOR { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<short> STATUS { get; set; }
    
        public virtual ICollection<REL_APP_PROJ> REL_APP_PROJ { get; set; }
        public virtual ICollection<REL_TEST_SUIT_PROJECT> REL_TEST_SUIT_PROJECT { get; set; }
        public virtual ICollection<T_PROJ_TC_MGR> T_PROJ_TC_MGR { get; set; }
        public virtual ICollection<T_PROJECT_DATA_SOURCE> T_PROJECT_DATA_SOURCE { get; set; }
    }
}
