//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST_ENUM
    {
        public long ENUM_ID { get; set; }
        public string ENUM_TYPE { get; set; }
        public string ENUM_VALUE { get; set; }
    }
}
