//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTGSTORYBOARD
    {
        public decimal ID { get; set; }
        public decimal FEEDPROCESSDETAILID { get; set; }
        public string TABNAME { get; set; }
        public Nullable<decimal> RUNORDER { get; set; }
        public string APPLICATIONNAME { get; set; }
        public string PROJECTNAME { get; set; }
        public string PROJECTDETAIL { get; set; }
        public string STORYBOARDNAME { get; set; }
        public string ACTIONNAME { get; set; }
        public string STEPNAME { get; set; }
        public string SUITENAME { get; set; }
        public string CASENAME { get; set; }
        public string DATASETNAME { get; set; }
        public string DEPENDENCY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<decimal> DEPENDENCYID { get; set; }
    }
}
