//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTGGUIOBJECT
    {
        public string OBJECTNAME { get; set; }
        public string TYPE { get; set; }
        public string QUICKACCESS { get; set; }
        public string PARENT { get; set; }
        public string OBJECTCOMMENT { get; set; }
        public string ENUMTYPE { get; set; }
        public string SQL { get; set; }
        public string APPLICATIONNAME { get; set; }
        public decimal FEEDPROCESSDETAILID { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
    }
}
