//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTGVARIABLE
    {
        public decimal ID { get; set; }
        public Nullable<decimal> FEEDPROCESSDETAILID { get; set; }
        public string NAME { get; set; }
        public string VALUE { get; set; }
        public string TYPE { get; set; }
        public string BASE_COMP { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<decimal> BASE_COMP_ID { get; set; }
    }
}
