//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MARS_STB_SNAPSHOT
    {
        public Nullable<long> STORYBOARD_ID { get; set; }
        public long STORYBOARD_DETAIL_ID { get; set; }
        public Nullable<long> LATEST_TEST_MARK_ID { get; set; }
        public Nullable<short> TEST_MODE { get; set; }
        public Nullable<long> HIST_ID { get; set; }
        public Nullable<long> RUN_ORDER { get; set; }
    }
}
