//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MARS_Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_USER_COMPANY
    {
        public decimal TESTER_ID { get; set; }
        public string TESTER_NAME_LAST { get; set; }
        public string TESTER_NAME_M { get; set; }
        public string TESTER_NAME_F { get; set; }
        public string TESTER_LOGIN_NAME { get; set; }
        public string TESTER_PWD { get; set; }
        public Nullable<decimal> AVAILABLE_MARK { get; set; }
        public string TESTER_MAIL { get; set; }
        public string TESTER_NUMBER { get; set; }
        public decimal COMPANY_ID { get; set; }
        public string TESTER_DESC { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_DESC { get; set; }
        public string COMPANY_ADDRESS { get; set; }
        public string COMPANY_NUMBER { get; set; }
        public Nullable<decimal> COMPANY_AVAILABLE_MARK { get; set; }
    }
}
